  GNU nano 6.2                    /etc/dnsmasq.conf                             
interface=enp4s0f1
interface=lo
bind-interfaces

# DHCP da Jetson
dhcp-range=192.168.10.50,192.168.10.150,255.255.255.0,24h
dhcp-host=48:b0:2d:2f:e9:b9,192.168.10.10
dhcp-option=3,192.168.10.1
dhcp-option=6,192.168.10.1,8.8.8.8,1.1.1.1

#Apontamento do domínio local direto para o servidor
address=/telemetry.local/192.168.10.1
domain-needed
bogus-priv

#Servidores DNS eexternos par onde o dnsmasq encaminha o que não for .local
server=143.106.9.2
server=8.8.8.8
server=8.8.4.4
